# -*- coding: utf-8 -*-
import json, random
random.seed(42)

sentences = []
sid = 1
def add(en, vi, category, topic, level):
    global sid
    sentences.append({"id": sid, "en": en.strip(), "vi": vi.strip(), "category": category, "topic": topic, "level": level})
    sid += 1

# ---------- 1. GREETING / SMALL TALK (100) ----------
greet = [
("Good morning! How are you today?","Chào buổi sáng! Hôm nay bạn khỏe không?"),
("Good afternoon! Nice to see you.","Chào buổi chiều! Rất vui được gặp bạn."),
("Good evening! How was your day?","Chào buổi tối! Hôm nay của bạn thế nào?"),
("Hi! Long time no see.","Chào! Lâu rồi không gặp."),
("Hey! How's it going?","Chào! Dạo này sao rồi?"),
("What's up?","Có gì mới không?"),
("How have you been lately?","Dạo này bạn thế nào?"),
("I'm doing great, thanks. And you?","Tôi rất khỏe, cảm ơn. Còn bạn?"),
("Not bad. How about you?","Cũng ổn. Còn bạn thì sao?"),
("Pretty good! Thanks for asking.","Khá tốt! Cảm ơn bạn đã hỏi."),
("Nice to meet you!","Rất vui được gặp bạn!"),
("Nice to meet you too!","Tôi cũng rất vui được gặp bạn!"),
("Welcome to Vietnam!","Chào mừng bạn đến Việt Nam!"),
("How was your weekend?","Cuối tuần của bạn thế nào?"),
("My weekend was wonderful, thanks.","Cuối tuần của tôi rất tuyệt, cảm ơn."),
("What did you do last weekend?","Cuối tuần trước bạn đã làm gì?"),
("I stayed at home and rested.","Tôi ở nhà và nghỉ ngơi."),
("I went out with my friends.","Tôi đã đi chơi với bạn bè."),
("Have a nice day!","Chúc bạn một ngày tốt lành!"),
("Have a great weekend!","Chúc bạn cuối tuần vui vẻ!"),
("Take care!","Giữ gìn sức khỏe nhé!"),
("See you soon!","Hẹn sớm gặp lại!"),
("See you tomorrow!","Hẹn gặp bạn ngày mai!"),
("Good night! Sleep well.","Chúc ngủ ngon! Ngủ ngon nhé."),
("How old are you?","Bạn bao nhiêu tuổi?"),
("I'm twenty-five years old.","Tôi hai mươi lăm tuổi."),
("Where are you from?","Bạn đến từ đâu?"),
("I'm from Hanoi, Vietnam.","Tôi đến từ Hà Nội, Việt Nam."),
("Where do you live?","Bạn sống ở đâu?"),
("I live in Ho Chi Minh City.","Tôi sống ở Thành phố Hồ Chí Minh."),
("What do you do for a living?","Bạn làm nghề gì?"),
("I work as a software engineer.","Tôi làm kỹ sư phần mềm."),
("Are you married?","Bạn đã kết hôn chưa?"),
("No, I'm still single.","Chưa, tôi vẫn còn độc thân."),
("Do you have any siblings?","Bạn có anh chị em không?"),
("Yes, I have one younger sister.","Có, tôi có một em gái."),
("What are your hobbies?","Sở thích của bạn là gì?"),
("I like reading books and swimming.","Tôi thích đọc sách và bơi lội."),
("I enjoy listening to music.","Tôi thích nghe nhạc."),
("Do you like sports?","Bạn có thích thể thao không?"),
("Yes, I love playing football.","Có, tôi rất thích đá bóng."),
("What kind of music do you like?","Bạn thích loại nhạc nào?"),
("I like pop and acoustic music.","Tôi thích nhạc pop và acoustic."),
("How's the weather today?","Hôm nay thời tiết thế nào?"),
("It's sunny and warm today.","Hôm nay trời nắng và ấm."),
("It's raining heavily outside.","Bên ngoài trời đang mưa to."),
("It's quite cold this morning.","Sáng nay trời khá lạnh."),
("I love this cool weather.","Tôi thích thời tiết mát mẻ này."),
("Excuse me, could you help me?","Xin lỗi, bạn có thể giúp tôi không?"),
("Of course! What do you need?","Dĩ nhiên! Bạn cần gì?"),
("Thank you so much!","Cảm ơn bạn rất nhiều!"),
("You're welcome!","Không có gì!"),
("I'm sorry, I'm late.","Xin lỗi, tôi đến muộn."),
("That's okay, don't worry.","Không sao đâu, đừng lo."),
("Congratulations on your new job!","Chúc mừng công việc mới của bạn!"),
("Thank you! I'm very excited.","Cảm ơn! Tôi rất háo hức."),
("Good luck with your exam!","Chúc bạn thi tốt!"),
("Thanks! I'll do my best.","Cảm ơn! Tôi sẽ cố gắng hết sức."),
("Happy birthday to you!","Chúc mừng sinh nhật bạn!"),
("Happy New Year!","Chúc mừng năm mới!"),
("Merry Christmas!","Giáng sinh vui vẻ!"),
("Have a safe trip!","Chúc bạn chuyến đi an toàn!"),
("Welcome home!","Chào mừng bạn về nhà!"),
("Make yourself at home.","Cứ tự nhiên như ở nhà nhé."),
("Can I offer you something to drink?","Tôi mời bạn uống gì nhé?"),
("A cup of tea, please.","Cho tôi một tách trà."),
("How do you feel today?","Hôm nay bạn cảm thấy thế nào?"),
("I feel a bit tired today.","Hôm nay tôi thấy hơi mệt."),
("You look great today!","Hôm nay trông bạn tuyệt lắm!"),
("Thanks, you too!","Cảm ơn, bạn cũng vậy!"),
("What time is it now?","Bây giờ là mấy giờ?"),
("It's half past seven.","Bây giờ là bảy giờ rưỡi."),
("Sorry, I didn't catch that.","Xin lỗi, tôi nghe chưa rõ."),
("Could you speak more slowly?","Bạn có thể nói chậm hơn không?"),
("Could you repeat that, please?","Bạn có thể nhắc lại không?"),
("What does this word mean?","Từ này nghĩa là gì?"),
("How do you spell your name?","Bạn đánh vần tên mình thế nào?"),
("My phone number is 090-123-4567.","Số điện thoại của tôi là 090-123-4567."),
("Could I have your email address?","Cho tôi xin địa chỉ email của bạn được không?"),
("Let's keep in touch!","Chúng ta giữ liên lạc nhé!"),
("Sure! Let's meet for coffee sometime.","Chắc chắn rồi! Hôm nào gặp nhau cà phê nhé."),
("It was nice talking to you.","Rất vui được trò chuyện với bạn."),
("Me too! See you again soon.","Tôi cũng vậy! Sớm gặp lại nhé."),
("Sorry, I have to go now.","Xin lỗi, giờ tôi phải đi rồi."),
("No problem. Talk to you later!","Không sao. Nói chuyện sau nhé!"),
("Please let me know if you need anything.","Nếu cần gì thì cho tôi biết nhé."),
("I really appreciate your help.","Tôi thực sự cảm kích sự giúp đỡ của bạn."),
("No worries, happy to help!","Không sao, rất vui được giúp!"),
("That's very kind of you.","Bạn thật tốt bụng."),
("I had a great time today.","Hôm nay tôi đã có khoảng thời gian tuyệt vời."),
("Let's hang out again next week.","Tuần sau lại đi chơi tiếp nhé."),
("Sounds great!","Nghe tuyệt đấy!"),
("I'm looking forward to it.","Tôi rất mong chờ điều đó."),
("By the way, how is your family?","Nhân tiện, gia đình bạn thế nào?"),
("Everyone is fine, thank you.","Mọi người đều khỏe, cảm ơn."),
("Please send my regards to your parents.","Cho tôi gửi lời hỏi thăm bố mẹ bạn nhé."),
("I will. Thanks!","Tôi sẽ chuyển lời. Cảm ơn!"),
("Is this your first time in Vietnam?","Đây có phải lần đầu bạn đến Việt Nam không?"),
("Yes, and I love it here!","Đúng vậy, và tôi rất thích nơi này!"),
("How long will you stay here?","Bạn sẽ ở đây bao lâu?"),
("I'll stay for two weeks.","Tôi sẽ ở lại hai tuần."),
("Enjoy your stay!","Chúc bạn có kỳ nghỉ vui vẻ!"),
("Thanks a lot!","Cảm ơn nhiều!"),
]
for en, vi in greet:
    lvl = "A1" if sid <= 35 else ("A2" if sid <= 70 else "B1")
    add(en, vi, "daily", "Chào hỏi & xã giao", lvl)

# ---------- 2. DAILY LIFE (100) ----------
daily = [
("I wake up at six o'clock every morning.","Tôi thức dậy lúc sáu giờ mỗi sáng."),
("I brush my teeth twice a day.","Tôi đánh răng hai lần mỗi ngày."),
("I take a shower in the morning.","Tôi tắm vào buổi sáng."),
("I have breakfast with my family.","Tôi ăn sáng cùng gia đình."),
("I usually have bread and eggs for breakfast.","Tôi thường ăn bánh mì và trứng vào bữa sáng."),
("I go to work by motorbike.","Tôi đi làm bằng xe máy."),
("It takes me thirty minutes to get to work.","Tôi mất ba mươi phút để đến chỗ làm."),
("Traffic is terrible this morning.","Sáng nay kẹt xe kinh khủng."),
("I start work at eight o'clock.","Tôi bắt đầu làm việc lúc tám giờ."),
("I check my emails first thing in the morning.","Việc đầu tiên buổi sáng là tôi kiểm tra email."),
("I have a meeting at ten o'clock.","Tôi có cuộc họp lúc mười giờ."),
("Let's have lunch together.","Chúng ta cùng ăn trưa nhé."),
("What do you want for lunch?","Bạn muốn ăn gì cho bữa trưa?"),
("I'd like a bowl of pho.","Tôi muốn một tô phở."),
("This restaurant is very clean.","Nhà hàng này rất sạch sẽ."),
("The food here is delicious.","Món ăn ở đây rất ngon."),
("Could I have the bill, please?","Cho tôi xin hóa đơn."),
("I finish work at five thirty.","Tôi tan làm lúc năm giờ rưỡi."),
("I go to the gym after work.","Tôi đi tập gym sau giờ làm."),
("I cook dinner at home.","Tôi nấu bữa tối ở nhà."),
("My mother is a great cook.","Mẹ tôi nấu ăn rất ngon."),
("We watch TV after dinner.","Chúng tôi xem TV sau bữa tối."),
("I help my kids with homework.","Tôi giúp con làm bài tập."),
("I go to bed at eleven p.m.","Tôi đi ngủ lúc mười một giờ đêm."),
("I usually sleep eight hours a night.","Tôi thường ngủ tám tiếng mỗi đêm."),
("I set an alarm for six a.m.","Tôi đặt báo thức lúc sáu giờ sáng."),
("I forgot my keys at home.","Tôi để quên chìa khóa ở nhà."),
("I need to buy some groceries.","Tôi cần mua một ít đồ tạp hóa."),
("The supermarket is near my house.","Siêu thị gần nhà tôi."),
("Milk and eggs are on sale today.","Sữa và trứng hôm nay giảm giá."),
("I do the laundry on weekends.","Tôi giặt đồ vào cuối tuần."),
("I clean my room every Sunday.","Tôi dọn phòng mỗi Chủ nhật."),
("Can you help me clean the house?","Bạn giúp tôi dọn nhà được không?"),
("Sure, I'd be happy to.","Chắc chắn rồi, tôi rất sẵn lòng."),
("Don't forget to turn off the lights.","Đừng quên tắt đèn nhé."),
("Please lock the door when you leave.","Vui lòng khóa cửa khi bạn ra ngoài."),
("I water the plants every evening.","Tôi tưới cây mỗi buổi tối."),
("My dog needs a walk.","Con chó của tôi cần được dắt đi dạo."),
("I feed my cat twice a day.","Tôi cho mèo ăn hai lần mỗi ngày."),
("I take my kids to school.","Tôi đưa con đi học."),
("School starts at seven fifteen.","Trường học bắt đầu lúc bảy giờ mười lăm."),
("My son likes mathematics very much.","Con trai tôi rất thích môn toán."),
("She is doing her homework now.","Cô ấy đang làm bài tập."),
("Please be quiet, the baby is sleeping.","Hãy giữ yên lặng, em bé đang ngủ."),
("I need to see a doctor.","Tôi cần đi khám bác sĩ."),
("I have a headache and fever.","Tôi bị đau đầu và sốt."),
("You should drink more water.","Bạn nên uống nhiều nước hơn."),
("Take this medicine twice daily.","Uống thuốc này hai lần mỗi ngày."),
("Get well soon!","Mau khỏe nhé!"),
("I have an appointment with the dentist.","Tôi có lịch hẹn với nha sĩ."),
("My back hurts from sitting too long.","Lưng tôi đau vì ngồi quá lâu."),
("You should exercise regularly.","Bạn nên tập thể dục thường xuyên."),
("I go jogging every morning.","Tôi chạy bộ mỗi sáng."),
("Walking is good for your health.","Đi bộ tốt cho sức khỏe."),
("I need to charge my phone.","Tôi cần sạc điện thoại."),
("My phone is out of battery.","Điện thoại tôi hết pin."),
("The Wi-Fi is very slow today.","Hôm nay Wi-Fi rất chậm."),
("Could I use your charger?","Tôi mượn sạc của bạn được không?"),
("I lost my wallet yesterday.","Hôm qua tôi làm mất ví."),
("Did you find your keys?","Bạn đã tìm thấy chìa khóa chưa?"),
("I left my umbrella on the bus.","Tôi để quên ô trên xe buýt."),
("Someone took my seat.","Ai đó đã ngồi mất chỗ của tôi."),
("Please line up over here.","Vui lòng xếp hàng ở đây."),
("It's my turn now.","Đến lượt tôi rồi."),
("Be careful! The floor is wet.","Cẩn thận! Sàn nhà ướt."),
("Watch out for the motorbikes!","Cẩn thận xe máy!"),
("Let's go for a walk in the park.","Chúng ta đi dạo công viên nhé."),
("The park is full of people today.","Hôm nay công viên rất đông."),
("My kids love the playground.","Con tôi rất thích sân chơi."),
("I need a haircut.","Tôi cần cắt tóc."),
("This barbershop is excellent.","Tiệm cắt tóc này rất tốt."),
("How much is a haircut?","Cắt tóc giá bao nhiêu?"),
("I want to send this package.","Tôi muốn gửi bưu kiện này."),
("How long will delivery take?","Giao hàng mất bao lâu?"),
("Please sign here.","Vui lòng ký tên ở đây."),
("I need to pay the electricity bill.","Tôi cần đóng tiền điện."),
("The rent is due next week.","Tiền thuê nhà đến hạn tuần sau."),
("I opened a new bank account.","Tôi vừa mở tài khoản ngân hàng mới."),
("The ATM is out of service.","Máy ATM đang ngừng hoạt động."),
("Could I withdraw some money?","Tôi có thể rút ít tiền không?"),
("I saved money for a new laptop.","Tôi để dành tiền mua laptop mới."),
("Gas prices went up again.","Giá xăng lại tăng."),
("My motorbike needs repair.","Xe máy của tôi cần sửa."),
("The mechanic fixed it yesterday.","Thợ đã sửa nó hôm qua."),
("I wash my motorbike every week.","Tôi rửa xe máy mỗi tuần."),
("Please drive safely!","Lái xe cẩn thận nhé!"),
("Don't drink and drive.","Đừng uống rượu khi lái xe."),
("Wear your helmet, please.","Hãy đội mũ bảo hiểm nhé."),
("I arrived home safely.","Tôi đã về nhà an toàn."),
("Dinner is ready!","Cơm tối xong rồi!"),
("Let's eat together.","Chúng ta cùng ăn nhé."),
("Help yourself!","Cứ tự nhiên nhé!"),
("I'm full, thank you.","Tôi no rồi, cảm ơn."),
("I'll wash the dishes.","Tôi sẽ rửa bát."),
("Good night, everyone!","Chúc cả nhà ngủ ngon!"),
("Sweet dreams!","Mơ đẹp nhé!"),
("See you in the morning.","Sáng mai gặp nhé."),
("Don't stay up too late.","Đừng thức khuya quá nhé."),
("I had a long but happy day.","Tôi đã có một ngày dài nhưng vui vẻ."),
("Tomorrow will be a better day.","Ngày mai sẽ là một ngày tốt hơn."),
]
for en, vi in daily:
    add(en, vi, "daily", "Sinh hoạt hàng ngày", "A1" if len(sentences)<150 else "A2")

# ---------- 3. FOOD & DRINK (100) ----------
food_base = [
("I'm hungry. Let's eat something.","Tôi đói rồi. Ăn gì đi."),
("I'm thirsty. I need some water.","Tôi khát. Tôi cần chút nước."),
("What would you like to eat?","Bạn muốn ăn gì?"),
("I feel like eating noodles tonight.","Tối nay tôi thèm ăn mì."),
("Vietnamese food is amazing.","Món ăn Việt Nam tuyệt vời."),
("Pho is my favorite dish.","Phở là món yêu thích của tôi."),
("Banh mi is cheap and tasty.","Bánh mì rẻ mà ngon."),
("Have you ever tried bun cha?","Bạn đã từng thử bún chả chưa?"),
("Spring rolls are crispy and fresh.","Nem rán giòn và tươi."),
("This soup is too salty.","Món canh này hơi mặn."),
("This dish is a bit spicy for me.","Món này hơi cay với tôi."),
("Could you make it less spicy?","Bạn làm ít cay lại được không?"),
("No sugar in my coffee, please.","Cà phê của tôi không đường nhé."),
("I'd like my coffee with condensed milk.","Tôi muốn cà phê sữa đá."),
("Egg coffee is a must-try in Hanoi.","Cà phê trứng là món phải thử ở Hà Nội."),
("Would you like some more rice?","Bạn có muốn thêm cơm không?"),
("Yes, just a little more.","Có, cho tôi thêm một ít."),
("No thanks, I'm full.","Thôi cảm ơn, tôi no rồi."),
("This mango is so sweet.","Quả xoài này ngọt quá."),
("I love tropical fruits.","Tôi thích trái cây nhiệt đới."),
("Let's order some seafood.","Chúng ta gọi ít hải sản đi."),
("Grilled fish is delicious here.","Cá nướng ở đây rất ngon."),
("How much is this dish?","Món này giá bao nhiêu?"),
("The menu, please.","Cho tôi xem thực đơn."),
("Do you have a vegetarian option?","Ở đây có món chay không?"),
("I'm allergic to peanuts.","Tôi bị dị ứng đậu phộng."),
("Is this dish very spicy?","Món này có cay lắm không?"),
("Just a little spicy.","Chỉ hơi cay thôi."),
("I'll have the same as him.","Tôi lấy giống món của anh ấy."),
("One more beer, please.","Cho thêm một chai bia nữa."),
("Cheers! To our friendship!","Dô! Vì tình bạn của chúng ta!"),
("Bottoms up!","Cạn ly!"),
("This restaurant has great service.","Nhà hàng này phục vụ rất tốt."),
("We need to book a table first.","Chúng ta cần đặt bàn trước."),
("I booked a table for four.","Tôi đã đặt bàn cho bốn người."),
("The table by the window, please.","Cho tôi bàn cạnh cửa sổ."),
("Can we sit outside?","Chúng ta ngồi ngoài trời được không?"),
("Smoking is not allowed here.","Ở đây không được hút thuốc."),
("Where is the restroom?","Nhà vệ sinh ở đâu?"),
("It's over there, on the left.","Ở đằng kia, bên trái."),
("The bill, please.","Tính tiền giúp tôi."),
("Can we pay separately?","Chúng ta chia tiền riêng được không?"),
("I'll pay this time.","Lần này để tôi trả."),
("No, let me pay.","Không, để tôi trả."),
("Let's split the bill.","Chúng ta chia đều nhé."),
("Keep the change.","Khỏi thối lại."),
("Do you accept credit cards?","Ở đây có nhận thẻ không?"),
("Sorry, cash only.","Xin lỗi, chỉ nhận tiền mặt."),
("Breakfast is served from 6 to 9.","Bữa sáng phục vụ từ 6 đến 9 giờ."),
("What time does the kitchen close?","Bếp đóng cửa lúc mấy giờ?"),
("I skipped breakfast this morning.","Sáng nay tôi bỏ bữa sáng."),
("Let's grab a quick lunch.","Ăn trưa nhanh thôi."),
("I brought lunch from home.","Tôi mang cơm trưa từ nhà."),
("Leftovers taste even better.","Đồ ăn thừa hâm lại còn ngon hơn."),
("My wife cooks very well.","Vợ tôi nấu ăn rất ngon."),
("This recipe needs more garlic.","Công thức này cần thêm tỏi."),
("Add a pinch of salt.","Thêm một nhúm muối."),
("Stir it well and serve hot.","Khuấy đều và dùng nóng."),
("Boil the noodles for five minutes.","Luộc mì trong năm phút."),
("Fry the eggs until golden.","Chiên trứng đến khi vàng."),
("Cut the vegetables into small pieces.","Cắt rau củ thành miếng nhỏ."),
("I learned to cook from YouTube.","Tôi học nấu ăn từ YouTube."),
("Let's have hotpot this weekend.","Cuối tuần này ăn lẩu nhé."),
("Barbecue night sounds perfect.","Tối nướng BBQ nghe hoàn hảo đấy."),
("I'll buy snacks for the movie.","Tôi sẽ mua đồ ăn vặt để xem phim."),
("Popcorn and coke, please.","Cho tôi bắp rang và coca."),
("This bubble tea is too sweet.","Trà sữa này ngọt quá."),
("Less ice, please.","Ít đá thôi nhé."),
("Extra toppings, please.","Thêm topping nhé."),
("I prefer hot tea in the morning.","Buổi sáng tôi thích trà nóng."),
("Green tea is good for health.","Trà xanh tốt cho sức khỏe."),
("Don't drink coffee too late.","Đừng uống cà phê quá muộn."),
("I can't sleep if I drink coffee.","Uống cà phê là tôi mất ngủ."),
("Let's meet for breakfast tomorrow.","Sáng mai gặp nhau ăn sáng nhé."),
("The cafe near my office is cozy.","Quán cà phê gần văn phòng tôi rất ấm cúng."),
("This cake is homemade.","Bánh này là nhà làm."),
("Happy eating! Enjoy your meal!","Chúc ngon miệng!"),
("Bon appétit!","Chúc ngon miệng!"),
(" seconds, please! This is so good.","Cho tôi thêm nữa! Ngon quá."),
("I'm on a diet, so just salad.","Tôi đang ăn kiêng, chỉ salad thôi."),
("I try to eat more vegetables.","Tôi cố ăn nhiều rau hơn."),
("Fast food is convenient but unhealthy.","Đồ ăn nhanh tiện nhưng không tốt."),
("I drink two liters of water daily.","Mỗi ngày tôi uống hai lít nước."),
("Chewing slowly helps digestion.","Nhai chậm giúp tiêu hóa tốt."),
("Don't skip meals.","Đừng bỏ bữa."),
("Eat a balanced diet.","Hãy ăn uống cân bằng."),
("Too much sugar is bad for you.","Quá nhiều đường không tốt đâu."),
("I gained two kilos this month.","Tháng này tôi tăng hai ký."),
("I need to lose some weight.","Tôi cần giảm cân."),
("Morning exercise makes me hungry.","Tập buổi sáng làm tôi đói."),
("Let's cook together tonight.","Tối nay cùng nấu ăn nhé."),
("You chop, I'll stir-fry.","Bạn thái rau, tôi xào."),
("Dinner's ready in ten minutes.","Mười phút nữa cơm xong."),
("Set the table, please.","Dọn bàn ăn giúp nhé."),
("Wash your hands before eating.","Rửa tay trước khi ăn."),
("Don't talk with your mouth full.","Đừng nói khi miệng đầy thức ăn."),
("Pass me the fish sauce, please.","Đưa giúp tôi chai nước mắm."),
("This is the best com tam ever!","Đây là cơm tấm ngon nhất từ trước đến nay!"),
]
for en, vi in food_base:
    add(en, vi, "daily", "Ăn uống", "A1" if sid%3==0 else "A2")

# ---------- 4. TRAVEL (100) ----------
travel = [
("I love traveling around Vietnam.","Tôi thích đi du lịch khắp Việt Nam."),
("Ha Long Bay is breathtaking.","Vịnh Hạ Long đẹp nghẹt thở."),
("Hoi An is famous for lanterns.","Hội An nổi tiếng với đèn lồng."),
("Da Lat is cool all year round.","Đà Lạt mát mẻ quanh năm."),
("Where should we go this summer?","Hè này chúng ta đi đâu?"),
("Let's go to the beach!","Đi biển đi!"),
("I need to book a flight.","Tôi cần đặt vé máy bay."),
("Is this a direct flight?","Đây có phải chuyến bay thẳng không?"),
("My flight was delayed two hours.","Chuyến bay của tôi bị trễ hai tiếng."),
("Where is the check-in counter?","Quầy làm thủ tục ở đâu?"),
("I'd like a window seat.","Tôi muốn ghế cạnh cửa sổ."),
("Aisle seat, please.","Cho tôi ghế cạnh lối đi."),
("How much luggage can I bring?","Tôi được mang bao nhiêu hành lý?"),
("My suitcase is overweight.","Vali của tôi quá cân."),
("Where is the baggage claim?","Khu nhận hành lý ở đâu?"),
("I can't find my passport.","Tôi không tìm thấy hộ chiếu."),
("Please show me your visa.","Vui lòng cho xem visa."),
("How long are you staying?","Bạn ở lại bao lâu?"),
("I'm here for tourism.","Tôi đến du lịch."),
("Welcome! Enjoy your trip!","Chào mừng! Chúc chuyến đi vui vẻ!"),
("Where is the nearest hotel?","Khách sạn gần nhất ở đâu?"),
("I booked a room online.","Tôi đã đặt phòng online."),
("Do you have any vacant rooms?","Còn phòng trống không?"),
("I'd like a double room.","Tôi muốn phòng đôi."),
("How much per night?","Giá bao nhiêu một đêm?"),
("Does breakfast come with the room?","Giá phòng có kèm bữa sáng không?"),
("Check-out is at twelve noon.","Trả phòng lúc mười hai giờ trưa."),
("Could I have a wake-up call?","Gọi tôi dậy giúp nhé?"),
("The air conditioner doesn't work.","Máy lạnh không hoạt động."),
("Could I change rooms?","Tôi đổi phòng được không?"),
("Where is the train station?","Ga tàu ở đâu?"),
("When does the next bus leave?","Chuyến xe buýt tiếp theo khi nào?"),
("How do I get to the airport?","Làm sao ra sân bay?"),
("Take bus number 86 to the airport.","Bắt xe buýt số 86 ra sân bay."),
("How far is it from here?","Từ đây đến đó bao xa?"),
("It's about ten minutes by taxi.","Đi taxi khoảng mười phút."),
("How much is the taxi fare?","Tiền taxi hết bao nhiêu?"),
("Please turn on the meter.","Bật đồng hồ tính tiền giúp tôi."),
("Stop here, please.","Dừng ở đây giúp tôi."),
("Could you wait a moment?","Bạn chờ một lát được không?"),
("I'm lost. Can you help me?","Tôi bị lạc. Bạn giúp tôi được không?"),
("Show me on the map, please.","Chỉ giúp tôi trên bản đồ."),
("Go straight, then turn left.","Đi thẳng rồi rẽ trái."),
("It's next to the post office.","Nó ở cạnh bưu điện."),
("The museum opens at nine.","Bảo tàng mở cửa lúc chín giờ."),
("Admission is free on Sundays.","Chủ nhật vào cửa miễn phí."),
("Photography is not allowed inside.","Không được chụp ảnh bên trong."),
("This temple is five hundred years old.","Ngôi chùa này năm trăm năm tuổi."),
("The view from the top is amazing.","Nhìn từ đỉnh xuống tuyệt đẹp."),
("Let's take a group photo!","Chụp ảnh nhóm nào!"),
("Smile! Say cheese!","Cười lên! Cheese nào!"),
("My feet hurt from walking.","Đi bộ nhiều đau chân quá."),
("Let's take a short break.","Nghỉ một lát nhé."),
("I bought souvenirs for my family.","Tôi mua quà lưu niệm cho gia đình."),
("How much discount can you give?","Bạn bớt được bao nhiêu?"),
("That's too expensive.","Đắt quá."),
("Do you have something cheaper?","Có cái nào rẻ hơn không?"),
("I'll take this one.","Tôi lấy cái này."),
("Cash or card?","Tiền mặt hay thẻ?"),
("It's an emergency! Call an ambulance!","Khẩn cấp! Gọi cấp cứu!"),
("I need a doctor.","Tôi cần bác sĩ."),
("Where is the nearest pharmacy?","Hiệu thuốc gần nhất ở đâu?"),
("I feel dizzy.","Tôi thấy chóng mặt."),
("I have motion sickness.","Tôi bị say xe."),
("Be careful with your belongings.","Cẩn thận đồ đạc nhé."),
("Keep your passport safe.","Giữ hộ chiếu cẩn thận."),
("Travel insurance is important.","Bảo hiểm du lịch rất quan trọng."),
("I missed my flight.","Tôi bị lỡ chuyến bay."),
("The hotel lost my reservation.","Khách sạn làm mất đặt phòng của tôi."),
("The weather is perfect for traveling.","Thời tiết quá đẹp để đi du lịch."),
("Let's rent a motorbike to explore.","Thuê xe máy đi khám phá đi."),
("Do you have a map of the city?","Bạn có bản đồ thành phố không?"),
("What places should I visit?","Tôi nên thăm những đâu?"),
("You must try the street food.","Bạn nhất định phải thử món đường phố."),
("Night market is very lively.","Chợ đêm rất nhộn nhịp."),
("Bargaining is normal here.","Mặc cả ở đây là bình thường."),
("I extended my stay one more day.","Tôi ở thêm một ngày nữa."),
("I don't want to go home yet.","Tôi chưa muốn về."),
("This trip was unforgettable.","Chuyến đi này thật khó quên."),
("I took hundreds of photos.","Tôi đã chụp hàng trăm tấm ảnh."),
("Let's travel together again!","Lần sau lại đi cùng nhau nhé!"),
("When is the return flight?","Chuyến bay về khi nào?"),
("Arrive early to avoid traffic.","Đến sớm để tránh kẹt xe."),
("Don't forget your boarding pass.","Đừng quên thẻ lên máy bay."),
("Boarding starts in ten minutes.","Mười phút nữa lên máy bay."),
("Please fasten your seatbelt.","Vui lòng thắt dây an toàn."),
("Turn off electronic devices, please.","Vui lòng tắt thiết bị điện tử."),
("We landed safely.","Chúng ta đã hạ cánh an toàn."),
("Welcome back home!","Chào mừng về nhà!"),
("How was your trip?","Chuyến đi của bạn thế nào?"),
("It was fantastic!","Tuyệt vời!"),
("I'm jet-lagged.","Tôi bị lệch múi giờ."),
("I need a good rest.","Tôi cần nghỉ ngơi."),
("Share your travel photos with me!","Chia sẻ ảnh du lịch với tôi nhé!"),
("Where to next?","Điểm đến tiếp theo ở đâu?"),
("Sapa in winter is magical.","Sapa mùa đông đẹp như cổ tích."),
("Phu Quoc has crystal-clear water.","Phú Quốc có nước biển trong vắt."),
("Mekong Delta is worth visiting.","Đồng bằng sông Cửu Long đáng để thăm."),
("Hue has beautiful ancient palaces.","Huế có cung điện cổ tuyệt đẹp."),
]
for en, vi in travel:
    add(en, vi, "daily", "Du lịch", "A2")

# ---------- 5. SHOPPING (100) ----------
shop = [
("Let's go shopping this afternoon.","Chiều nay đi mua sắm nhé."),
("The mall opens at nine a.m.","Trung tâm thương mại mở cửa lúc chín giờ sáng."),
("I'm just looking, thanks.","Tôi chỉ xem thôi, cảm ơn."),
("Do you have this in another color?","Cái này có màu khác không?"),
("Do you have a larger size?","Có size lớn hơn không?"),
("Do you have a smaller size?","Có size nhỏ hơn không?"),
("Can I try this on?","Tôi thử cái này được không?"),
("Where is the fitting room?","Phòng thử đồ ở đâu?"),
("It fits perfectly!","Vừa khít luôn!"),
("It's too tight.","Nó hơi chật."),
("It's too loose.","Nó hơi rộng."),
("How much is this shirt?","Áo này giá bao nhiêu?"),
("It's two hundred thousand dong.","Giá hai trăm nghìn đồng."),
("That's a bit pricey.","Hơi đắt một chút."),
("Can you lower the price?","Bạn bớt chút được không?"),
("Final price, please.","Giá chốt đi."),
("Deal! I'll take it.","Chốt! Tôi lấy."),
("Do you offer warranty?","Có bảo hành không?"),
("One-year warranty included.","Kèm bảo hành một năm."),
("Can I return this if faulty?","Lỗi thì đổi được không?"),
("Here's your receipt.","Đây là hóa đơn của bạn."),
("Do you have a loyalty card?","Bạn có thẻ thành viên không?"),
("Points can be redeemed later.","Điểm tích lũy đổi quà sau."),
("There's a big sale this weekend.","Cuối tuần này sale lớn."),
("Everything is fifty percent off.","Mọi thứ giảm năm mươi phần trăm."),
("Buy one get one free.","Mua một tặng một."),
("Limited stock! Hurry up!","Số lượng có hạn! Nhanh lên!"),
("I ordered it online.","Tôi đã đặt online."),
("Free shipping for orders over 500k.","Miễn phí ship cho đơn trên 500k."),
("Cash on delivery, please.","Cho tôi thanh toán khi nhận hàng."),
("My package hasn't arrived yet.","Gói hàng của tôi chưa tới."),
("Track your order in the app.","Theo dõi đơn trong app nhé."),
("I want to cancel my order.","Tôi muốn hủy đơn."),
("This item is out of stock.","Món này hết hàng."),
("It will be back next week.","Tuần sau hàng về."),
("I need to buy a birthday gift.","Tôi cần mua quà sinh nhật."),
("Could you wrap it as a gift?","Gói quà giúp tôi được không?"),
("This phone case is nice.","Ốp điện thoại này đẹp."),
("How long does the battery last?","Pin dùng được bao lâu?"),
("I need a new pair of shoes.","Tôi cần đôi giày mới."),
("These sneakers are comfortable.","Đôi sneaker này thoải mái."),
("I prefer cotton material.","Tôi thích chất liệu cotton."),
("Is this machine washable?","Cái này giặt máy được không?"),
("Dry clean only.","Chỉ giặt khô."),
("I bought fresh vegetables today.","Hôm nay tôi mua rau tươi."),
("The market is cheaper than the mall.","Chợ rẻ hơn trung tâm thương mại."),
("Can I pay by e-wallet?","Tôi trả bằng ví điện tử được không?"),
("We accept Momo and ZaloPay.","Chúng tôi nhận Momo và ZaloPay."),
("The QR code isn't working.","Mã QR không hoạt động."),
("Please enter your PIN.","Vui lòng nhập mã PIN."),
("Payment successful!","Thanh toán thành công!"),
("I'd like a refund, please.","Tôi muốn hoàn tiền."),
("The zipper is broken.","Khóa kéo bị hỏng."),
("Could I exchange this?","Tôi đổi cái khác được không?"),
("No exchange without receipt.","Không có hóa đơn thì không đổi được."),
("Customer service is on floor two.","Chăm sóc khách hàng ở tầng hai."),
("What time do you close?","Mấy giờ đóng cửa?"),
("We close at ten p.m.","Mười giờ tối đóng cửa."),
("New arrivals just came in.","Hàng mới vừa về."),
("This brand is very popular.","Thương hiệu này rất nổi."),
("It's genuine leather.","Đây là da thật."),
("Is this on sale?","Cái này đang giảm giá à?"),
("The price tag says 30% off.","Tem giá ghi giảm 30%."),
("I compared prices online first.","Tôi đã so giá online trước."),
("Reviews for this product are great.","Sản phẩm này được đánh giá tốt."),
("One star? That sounds bad.","Một sao? Nghe tệ nhỉ."),
("I always read reviews before buying.","Tôi luôn đọc review trước khi mua."),
("Add to cart.","Thêm vào giỏ hàng."),
("Proceed to checkout.","Tiến hành thanh toán."),
("Apply the discount code.","Áp mã giảm giá."),
("The code has expired.","Mã đã hết hạn."),
("I got free vouchers.","Tôi có voucher miễn phí."),
("Same-day delivery available.","Có giao hàng trong ngày."),
("Please leave it at the door.","Để hàng trước cửa giúp tôi."),
("Call me when you arrive.","Đến thì gọi tôi nhé."),
("Rate your shopping experience.","Đánh giá trải nghiệm mua sắm nhé."),
("Five stars! Highly recommended!","Năm sao! Rất đáng mua!"),
("I need school supplies.","Tôi cần đồ dùng học tập."),
("Backpacks are on the third floor.","Balo ở tầng ba."),
("Stationery is buy-two-get-one.","Văn phòng phẩm mua hai tặng một."),
("This laptop is for students.","Laptop này dành cho sinh viên."),
("What specs do you need?","Bạn cần cấu hình thế nào?"),
("Eight gigs of RAM minimum.","Tối thiểu 8GB RAM."),
("The screen is full HD.","Màn hình full HD."),
("It comes with a free mouse.","Tặng kèm chuột."),
("Install Office for me, please.","Cài Office giúp tôi nhé."),
("I need a phone charger.","Tôi cần dây sạc điện thoại."),
("This cable charges very fast.","Cáp này sạc rất nhanh."),
("I love window shopping.","Tôi thích đi ngắm đồ."),
("I spent too much money today.","Hôm nay tôi tiêu nhiều tiền quá."),
("My wallet is empty now.","Ví tôi rỗng rồi."),
("Time to go home!","Đến giờ về nhà rồi!"),
("Shopping with friends is fun.","Đi mua sắm với bạn bè thật vui."),
]
for en, vi in shop:
    add(en, vi, "daily", "Mua sắm", "A2")

# ---------- 6. WORK OFFICE (100) ----------
office = [
("Good morning, everyone!","Chào buổi sáng mọi người!"),
("Did you check today's schedule?","Bạn đã xem lịch hôm nay chưa?"),
("We have a standup at nine.","Chúng ta họp standup lúc chín giờ."),
("The meeting starts in five minutes.","Cuộc họp bắt đầu trong năm phút."),
("Sorry I'm late, traffic was bad.","Xin lỗi tôi đến muộn, kẹt xe quá."),
("Let's get started.","Chúng ta bắt đầu nhé."),
("First item on the agenda...","Việc đầu tiên trong chương trình..."),
("Could you share your screen?","Bạn chia sẻ màn hình được không?"),
("Can everyone see my screen?","Mọi người thấy màn hình tôi chưa?"),
("You're on mute!","Bạn đang tắt mic!"),
("Sorry, my mic wasn't working.","Xin lỗi, mic của tôi bị lỗi."),
("My internet is unstable.","Mạng của tôi không ổn định."),
("Let me turn off my camera.","Để tôi tắt camera."),
("Please summarize the key points.","Vui lòng tóm tắt ý chính."),
("I'll send the meeting notes later.","Tôi sẽ gửi biên bản họp sau."),
("What's the deadline for this task?","Hạn chót của việc này là khi nào?"),
("The deadline is this Friday.","Hạn chót là thứ Sáu này."),
("We need to work overtime tonight.","Tối nay cần tăng ca."),
("I finished the report yesterday.","Hôm qua tôi đã xong báo cáo."),
("Please review my proposal.","Vui lòng xem đề xuất của tôi."),
("Looks good to me.","Tôi thấy ổn."),
("I have a few comments.","Tôi có vài nhận xét."),
("Let's discuss it after lunch.","Ăn trưa xong chúng ta bàn tiếp."),
("I agree with your idea.","Tôi đồng ý với ý tưởng của bạn."),
("I see your point, but...","Tôi hiểu ý bạn, nhưng..."),
("Let's vote on it.","Chúng ta bỏ phiếu nhé."),
("The majority agrees.","Đa số đồng ý."),
("I'll take care of this part.","Phần này để tôi lo."),
("Could you handle the client call?","Bạn nghe cuộc gọi khách hàng giúp nhé?"),
("I'll follow up with them tomorrow.","Ngày mai tôi sẽ liên hệ lại với họ."),
("The client approved the design.","Khách hàng đã duyệt thiết kế."),
("We lost a big contract.","Chúng ta mất một hợp đồng lớn."),
("Don't worry, we'll bounce back.","Đừng lo, chúng ta sẽ vực lại."),
("Our sales grew twenty percent.","Doanh số tăng hai mươi phần trăm."),
("Great job, team!","Cả nhóm làm tốt lắm!"),
("Let's celebrate tonight!","Tối nay ăn mừng nhé!"),
("I need a day off next Monday.","Tôi cần nghỉ thứ Hai tới."),
("Please submit your leave request.","Vui lòng gửi đơn xin nghỉ."),
("Approved. Enjoy your break!","Duyệt. Nghỉ ngơi vui vẻ!"),
("I'm feeling burnt out.","Tôi thấy kiệt sức."),
("You should take a vacation.","Bạn nên nghỉ phép."),
("My salary was paid today.","Hôm nay tôi nhận lương."),
("When is the performance review?","Khi nào đánh giá hiệu suất?"),
("I got a promotion!","Tôi được thăng chức!"),
("Congratulations! You deserve it!","Chúc mừng! Bạn xứng đáng!"),
("Welcome to the team!","Chào mừng đến với nhóm!"),
("Let me introduce our new member.","Để tôi giới thiệu thành viên mới."),
("He's our new designer.","Anh ấy là designer mới."),
("She'll support our marketing.","Cô ấy sẽ hỗ trợ marketing."),
("My desk is near the window.","Bàn tôi gần cửa sổ."),
("The printer is out of paper.","Máy in hết giấy."),
("Could you fix the projector?","Bạn sửa máy chiếu giúp được không?"),
("The meeting room is occupied.","Phòng họp đang có người."),
("Book another room, please.","Đặt phòng khác giúp nhé."),
("Lunch break is one hour.","Nghỉ trưa một tiếng."),
("Where shall we eat today?","Trưa nay ăn đâu?"),
("The canteen food is decent.","Đồ ăn căng tin cũng ổn."),
("I brought instant noodles.","Tôi mang mì tôm."),
("Coffee break in ten minutes.","Mười phút nữa nghỉ uống cà phê."),
("I need strong coffee to focus.","Tôi cần cà phê đậm để tập trung."),
("Don't disturb me, I'm in flow.","Đừng làm phiền, tôi đang tập trung."),
("I'll be back in five minutes.","Năm phút nữa tôi quay lại."),
("He's on a business trip.","Anh ấy đang đi công tác."),
("She works from home today.","Hôm nay cô ấy làm ở nhà."),
("Hybrid work is flexible.","Làm hybrid linh hoạt."),
("Clock in before nine, please.","Vui lòng chấm công trước chín giờ."),
("Don't forget to clock out.","Đừng quên chấm công ra về."),
("Overtime pay is double.","Lương tăng ca gấp đôi."),
("Submit expenses by month-end.","Nộp chi phí trước cuối tháng."),
("Keep all receipts.","Giữ lại mọi hóa đơn."),
("The boss wants to see you.","Sếp muốn gặp bạn."),
("Stay calm and be confident.","Bình tĩnh và tự tin nhé."),
("How did the interview go?","Phỏng vấn thế nào?"),
("They'll reply within a week.","Họ sẽ trả lời trong một tuần."),
("I resigned last month.","Tháng trước tôi đã nghỉ việc."),
("I'm looking for a new challenge.","Tôi tìm thử thách mới."),
("I updated my CV.","Tôi đã cập nhật CV."),
("Networking helps find jobs.","Quan hệ giúp tìm việc."),
("Dress formally for the interview.","Mặc lịch sự khi phỏng vấn."),
("Arrive ten minutes early.","Đến sớm mười phút."),
("Bring copies of your certificates.","Mang bản sao bằng cấp."),
("Tell me about yourself.","Hãy giới thiệu về bản thân."),
("My strength is problem-solving.","Điểm mạnh của tôi là giải quyết vấn đề."),
("My weakness? I'm a perfectionist.","Điểm yếu? Tôi cầu toàn."),
("Where do you see yourself in five years?","Năm năm nữa bạn thấy mình ở đâu?"),
("I want to become a team lead.","Tôi muốn thành team lead."),
("What are your salary expectations?","Mức lương mong muốn của bạn?"),
("Eight hundred dollars per month.","Tám trăm đô mỗi tháng."),
("When can you start?","Khi nào bạn bắt đầu được?"),
("I can start immediately.","Tôi bắt đầu ngay được."),
("We'll be in touch.","Chúng tôi sẽ liên lạc."),
("Thank you for your time.","Cảm ơn thời gian của bạn."),
("Teamwork makes the dream work.","Làm việc nhóm tạo nên thành công."),
("Communication is key.","Giao tiếp là chìa khóa."),
("Let's keep each other updated.","Cùng cập nhật cho nhau nhé."),
("No blame, just solutions.","Không đổ lỗi, chỉ giải pháp."),
("Learn from mistakes.","Học từ sai lầm."),
("Every feedback helps us grow.","Mọi góp ý giúp ta lớn lên."),
]
for en, vi in office:
    add(en, vi, "daily", "Công việc văn phòng", "B1")

# ---------- 7. TECH DEV (120) ----------
dev = [
("I work as a full-stack developer.","Tôi làm lập trình viên full-stack."),
("What programming languages do you know?","Bạn biết những ngôn ngữ lập trình nào?"),
("I mainly code in JavaScript and Python.","Tôi chủ yếu code JavaScript và Python."),
("TypeScript catches bugs early.","TypeScript giúp bắt lỗi sớm."),
("Python is great for beginners.","Python rất tốt cho người mới."),
("Which framework do you use?","Bạn dùng framework nào?"),
("We use React for the frontend.","Chúng tôi dùng React cho frontend."),
("Our backend is built with Node.js.","Backend của chúng tôi dùng Node.js."),
("The database is PostgreSQL.","Cơ sở dữ liệu là PostgreSQL."),
("We cache data with Redis.","Chúng tôi cache dữ liệu bằng Redis."),
("Clone the repo to get started.","Clone repo để bắt đầu."),
("Create a new branch for this feature.","Tạo nhánh mới cho tính năng này."),
("Commit your changes frequently.","Commit thay đổi thường xuyên."),
("Push your code and open a pull request.","Push code và mở pull request."),
("Please review my pull request.","Vui lòng review pull request của tôi."),
("There are merge conflicts to resolve.","Có conflict cần giải quyết."),
("Rebase onto the main branch.","Rebase lên nhánh main."),
("Squash your commits before merging.","Gộp commit trước khi merge."),
("The build is failing on CI.","Build đang lỗi trên CI."),
("All tests must pass before merging.","Mọi test phải pass trước khi merge."),
("Write unit tests for new code.","Viết unit test cho code mới."),
("Test coverage is above eighty percent.","Độ bao phủ test trên tám mươi phần trăm."),
("This function needs refactoring.","Hàm này cần refactor."),
("Avoid duplicating code.","Tránh lặp code."),
("Follow the naming conventions.","Tuân thủ quy ước đặt tên."),
("Add comments for complex logic.","Thêm comment cho logic phức tạp."),
("Remove the dead code.","Xóa code chết đi."),
("Format the code before committing.","Format code trước khi commit."),
("ESLint reported three errors.","ESLint báo ba lỗi."),
("Fix the linter warnings first.","Sửa cảnh báo linter trước."),
("The API returns JSON data.","API trả về dữ liệu JSON."),
("Check the response status code.","Kiểm tra mã trạng thái response."),
("We got a 404 Not Found error.","Chúng ta gặp lỗi 404 Not Found."),
("Handle the error gracefully.","Xử lý lỗi một cách mượt mà."),
("Log the error for debugging.","Log lỗi để debug."),
("Reproduce the bug first.","Tái hiện lỗi trước đã."),
("It works on my machine!","Máy tôi chạy được mà!"),
("Clear the cache and try again.","Xóa cache rồi thử lại."),
("Restart the server.","Khởi động lại server."),
("The server is down.","Server sập rồi."),
("Deploy to staging first.","Deploy lên staging trước."),
("Production deployment is tonight.","Tối nay deploy production."),
("Rollback if anything breaks.","Có sự cố thì rollback."),
("Monitor logs after deployment.","Theo dõi log sau khi deploy."),
("Set up alerts for downtime.","Cài cảnh báo khi downtime."),
("Use environment variables for secrets.","Dùng biến môi trường cho secret."),
("Never commit passwords to git.","Đừng bao giờ commit mật khẩu lên git."),
("Rotate the API keys regularly.","Xoay vòng API key định kỳ."),
("Enable two-factor authentication.","Bật xác thực hai lớp."),
("Hash passwords with bcrypt.","Hash mật khẩu bằng bcrypt."),
("Validate user input on both sides.","Validate input cả hai phía."),
("Sanitize data to prevent XSS.","Làm sạch dữ liệu để chống XSS."),
("Use HTTPS everywhere.","Dùng HTTPS mọi nơi."),
("The site loads in under two seconds.","Trang tải dưới hai giây."),
("Optimize images to reduce size.","Tối ưu ảnh để giảm dung lượng."),
("Lazy-load offscreen images.","Lazy-load ảnh ngoài màn hình."),
("Minify CSS and JavaScript.","Nén CSS và JavaScript."),
("Use a CDN for static assets.","Dùng CDN cho tài nguyên tĩnh."),
("Mobile-first design is essential.","Thiết kế mobile-first rất quan trọng."),
("Test on multiple browsers.","Test trên nhiều trình duyệt."),
("Fix the layout on small screens.","Sửa layout trên màn hình nhỏ."),
("The button is not clickable.","Nút này không bấm được."),
("Add a loading spinner here.","Thêm vòng xoay loading ở đây."),
("Show a friendly error message.","Hiện thông báo lỗi thân thiện."),
("Dark mode looks amazing!","Chế độ tối trông tuyệt!"),
("Support both light and dark themes.","Hỗ trợ cả theme sáng và tối."),
("Make the form accessible.","Làm form dễ tiếp cận."),
("Add labels to all inputs.","Thêm nhãn cho mọi ô nhập."),
("Keyboard navigation must work.","Điều hướng bàn phím phải hoạt động."),
("Docker makes deployment easy.","Docker giúp deploy dễ dàng."),
("Write a Dockerfile for the app.","Viết Dockerfile cho app."),
("Run containers with docker compose.","Chạy container bằng docker compose."),
("Kubernetes manages our clusters.","Kubernetes quản lý cluster của chúng tôi."),
("Scale up during peak hours.","Mở rộng quy mô giờ cao điểm."),
("Set resource limits for pods.","Đặt giới hạn tài nguyên cho pod."),
("CI/CD automates our releases.","CI/CD tự động hóa phát hành."),
("Every push triggers a pipeline.","Mỗi lần push chạy pipeline."),
("Blue-green deployment reduces risk.","Deploy blue-green giảm rủi ro."),
("Feature flags control rollouts.","Feature flag điều khiển phát hành."),
("A/B test the new design.","A/B test thiết kế mới."),
("Track user events with analytics.","Theo dõi sự kiện người dùng bằng analytics."),
("Respect user privacy (GDPR).","Tôn trọng quyền riêng tư (GDPR)."),
("Back up the database daily.","Sao lưu database mỗi ngày."),
("Restore from backup if needed.","Khôi phục từ backup khi cần."),
("Migrate the schema carefully.","Migrate schema cẩn thận."),
("Add an index to speed up queries.","Thêm index để tăng tốc truy vấn."),
("This query is too slow.","Truy vấn này quá chậm."),
("Use pagination for large lists.","Dùng phân trang cho danh sách lớn."),
("Cache expensive computations.","Cache các tính toán tốn kém."),
("Rate-limit the login endpoint.","Giới hạn tốc độ endpoint đăng nhập."),
("Document the API with Swagger.","Ghi tài liệu API bằng Swagger."),
("Keep the README up to date.","Cập nhật README thường xuyên."),
("Onboard new devs with a guide.","Onboard dev mới bằng hướng dẫn."),
("Pair program on hard problems.","Pair programming cho bài khó."),
("Timebox the investigation to one hour.","Giới hạn tìm hiểu trong một giờ."),
("Rubber-duck debugging really works!","Debug kiểu vịt cao su hiệu quả thật!"),
("Take a break; the bug will surface.","Nghỉ chút đi; lỗi sẽ lộ ra."),
("Sleep on it and retry tomorrow.","Để mai nghĩ tiếp."),
("Google the exact error message.","Google đúng thông báo lỗi."),
("Read the docs before asking.","Đọc tài liệu trước khi hỏi."),
("Ask questions in the team channel.","Hỏi trong kênh nhóm."),
("Share what you learned today.","Chia sẻ điều bạn học hôm nay."),
("Tech debt slows us down.","Nợ kỹ thuật làm ta chậm lại."),
("Schedule time to pay down tech debt.","Dành thời gian trả nợ kỹ thuật."),
("Prototype quickly, then iterate.","Làm prototype nhanh rồi lặp lại."),
("Ship early, ship often.","Phát hành sớm, phát hành thường xuyên."),
("Done is better than perfect.","Xong tốt hơn hoàn hảo."),
("Keep it simple, stupid (KISS).","Giữ mọi thứ đơn giản (KISS)."),
("You aren't gonna need it (YAGNI).","Bạn sẽ không cần nó đâu (YAGNI)."),
("Separation of concerns matters.","Tách biệt trách nhiệm rất quan trọng."),
("Single responsibility principle!","Nguyên tắc đơn nhiệm!"),
("Don't repeat yourself (DRY).","Đừng lặp lại (DRY)."),
("Code is read more than written.","Code được đọc nhiều hơn viết."),
("Review code with empathy.","Review code với sự đồng cảm."),
("LGTM! Merging now.","LGTM! Merge đây."),
("Nice catch! Fixed.","Bắt lỗi hay! Đã sửa."),
("PTAL (please take another look).","PTAL (xem lại giúp)."),
]
for en, vi in dev:
    add(en, vi, "tech", "Lập trình & phát triển", "B1" if sid%2==0 else "B2")

# ---------- 8. TECH MEETING/EMAIL (100) ----------
meet = [
("Let's schedule a quick sync.","Lên lịch họp nhanh nhé."),
("Are you available tomorrow morning?","Sáng mai bạn rảnh không?"),
("Send me a calendar invite.","Gửi tôi lời mời lịch nhé."),
("The meeting link is in the invite.","Link họp trong lời mời."),
("Join five minutes early.","Vào sớm năm phút."),
("Let's go around and update.","Lần lượt cập nhật nhé."),
("Yesterday I finished the login page.","Hôm qua tôi xong trang đăng nhập."),
("Today I'll work on the dashboard.","Hôm nay tôi làm dashboard."),
("I'm blocked by the API issue.","Tôi đang kẹt ở vấn đề API."),
("I need help from the backend team.","Tôi cần backend hỗ trợ."),
("Let's take this offline.","Việc này bàn riêng sau nhé."),
("Action items: John will update docs.","Việc cần làm: John cập nhật tài liệu."),
("Any blockers?","Có vướng mắc gì không?"),
("No blockers on my side.","Phía tôi không vướng gì."),
("We're on track for Friday.","Chúng ta đúng tiến độ thứ Sáu."),
("We're slightly behind schedule.","Chúng ta hơi trễ tiến độ."),
("We need to cut scope.","Cần cắt bớt phạm vi."),
("Prioritize the must-have features.","Ưu tiên tính năng bắt buộc."),
("Nice demo! The UI is smooth.","Demo hay! UI mượt."),
("When will QA start testing?","Khi nào QA bắt đầu test?"),
("Log bugs in Jira, please.","Log bug lên Jira nhé."),
("Set the priority to critical.","Đặt mức ưu tiên critical."),
("Assign it to me.","Gán cho tôi."),
("I'll pick it up today.","Hôm nay tôi nhận việc đó."),
("Estimated two story points.","Ước tính hai story point."),
("Sprint planning is on Monday.","Họp kế hoạch sprint thứ Hai."),
("Retro is on Friday afternoon.","Họp retro chiều thứ Sáu."),
("What went well? What didn't?","Điều gì tốt? Điều gì chưa?"),
("We should improve estimation.","Chúng ta nên cải thiện ước tính."),
("Lessons learned: test earlier.","Bài học: test sớm hơn."),
("Thanks everyone for joining.","Cảm ơn mọi người đã tham gia."),
("Per my last email...","Theo email trước của tôi..."),
("Just following up on this.","Tôi chỉ nhắc lại việc này."),
("Looping in the product manager.","Tôi thêm quản lý sản phẩm vào."),
("Please find the report attached.","Vui lòng xem báo cáo đính kèm."),
("Let me know if you have questions.","Cho tôi biết nếu bạn có câu hỏi."),
("Looking forward to your reply.","Mong nhận phản hồi của bạn."),
("Best regards,","Trân trọng,"),
("Thanks and regards,","Cảm ơn và trân trọng,"),
("Subject: Request for approval","Tiêu đề: Xin phê duyệt"),
("Urgent: Server outage","Khẩn: Sập server"),
("FYI, the release is postponed.","Thông tin thêm, bản phát hành bị hoãn."),
("As discussed, here's the plan.","Như đã bàn, đây là kế hoạch."),
("Please confirm receipt.","Vui lòng xác nhận đã nhận."),
("Noted with thanks.","Đã ghi nhận, cảm ơn."),
("Well received.","Đã nhận được."),
("I'll get back to you soon.","Tôi sẽ phản hồi sớm."),
("Sorry for the late reply.","Xin lỗi vì trả lời muộn."),
("Thanks for your patience.","Cảm ơn sự kiên nhẫn của bạn."),
("Apologies for the inconvenience.","Xin lỗi vì sự bất tiện."),
("Could we reschedule to Thursday?","Dời sang thứ Năm được không?"),
("Thursday works for me.","Thứ Năm được với tôi."),
("Let's meet in person.","Gặp trực tiếp nhé."),
("The client wants a demo next week.","Khách hàng muốn demo tuần sau."),
("Prepare slides for the pitch.","Chuẩn bị slide thuyết trình."),
("Keep slides short and visual.","Slide ngắn gọn và trực quan."),
("Start with the problem statement.","Bắt đầu bằng phát biểu vấn đề."),
("Highlight the key metrics.","Nhấn mạnh chỉ số chính."),
("End with a clear call to action.","Kết thúc bằng lời kêu gọi rõ ràng."),
("Any questions from the audience?","Khán giả có câu hỏi nào không?"),
("Great question! Let me explain.","Câu hỏi hay! Để tôi giải thích."),
("I'll follow up with details.","Tôi sẽ gửi chi tiết sau."),
("Let's connect on LinkedIn.","Kết nối LinkedIn nhé."),
("I'll share my contact info.","Tôi chia sẻ thông tin liên lạc."),
("Minutes of meeting attached.","Đính kèm biên bản họp."),
("Next meeting: same time tomorrow.","Họp tiếp: giờ này ngày mai."),
("Standup is async today.","Hôm nay standup bất đồng bộ."),
("Post updates in Slack.","Đăng cập nhật lên Slack."),
("React with emoji to acknowledge.","Thả emoji để xác nhận."),
("Pin important messages.","Ghim tin nhắn quan trọng."),
("Create a thread to discuss.","Tạo luồng để thảo luận."),
("Avoid meetings without agenda.","Tránh họp không có chương trình."),
("This could have been an email.","Việc này gửi email là đủ."),
("Protect your focus time.","Bảo vệ thời gian tập trung."),
("No-meeting Wednesdays!","Thứ Tư không họp!"),
("Brainstorm freely; no judging.","Cứ nêu ý tưởng, không phán xét."),
("Vote with dots for best ideas.","Chấm điểm cho ý hay nhất."),
("Park that idea for later.","Gác ý đó lại sau."),
("Decide and commit.","Quyết định và cam kết."),
("Disagree and commit.","Không đồng ý nhưng vẫn cam kết."),
("Ownership means following through.","Trách nhiệm là theo đến cùng."),
("Over-communicate in remote teams.","Nhóm remote cần giao tiếp nhiều hơn."),
("Default to async communication.","Ưu tiên giao tiếp bất đồng bộ."),
("Document decisions in Notion.","Ghi quyết định lên Notion."),
("Update the roadmap quarterly.","Cập nhật roadmap mỗi quý."),
("Share progress every Friday.","Chia sẻ tiến độ mỗi thứ Sáu."),
("Celebrate small wins.","Ăn mừng chiến thắng nhỏ."),
("Shoutout to Linh for the fix!","Khen Linh vì bản fix!"),
("Kudos to the QA team!","Khen ngợi nhóm QA!"),
("Happy Friday, everyone!","Thứ Sáu vui vẻ mọi người!"),
]
for en, vi in meet:
    add(en, vi, "tech", "Họp & email công việc", "B1")

# ---------- 9. INTERVIEW (90) ----------
interview = [
("Tell me about your experience.","Hãy kể về kinh nghiệm của bạn."),
("I have three years of experience.","Tôi có ba năm kinh nghiệm."),
("I specialize in backend development.","Tôi chuyên về backend."),
("I'm passionate about clean code.","Tôi đam mê code sạch."),
("I led a team of four engineers.","Tôi đã dẫn nhóm bốn kỹ sư."),
("We shipped the product in six months.","Chúng tôi phát hành sản phẩm trong sáu tháng."),
("My biggest achievement is...","Thành tựu lớn nhất của tôi là..."),
("I reduced load time by forty percent.","Tôi đã giảm thời gian tải 40%."),
("I automated the deployment pipeline.","Tôi đã tự động hóa pipeline deploy."),
("I mentored junior developers.","Tôi đã hướng dẫn dev junior."),
("Explain REST vs GraphQL.","Giải thích REST và GraphQL."),
("REST uses multiple endpoints; GraphQL uses one.","REST dùng nhiều endpoint; GraphQL dùng một."),
("What is a closure in JavaScript?","Closure trong JavaScript là gì?"),
("A closure remembers outer variables.","Closure ghi nhớ biến bên ngoài."),
("Explain event loop briefly.","Giải thích ngắn về event loop."),
("How does garbage collection work?","Thu gom rác hoạt động thế nào?"),
("Difference between SQL and NoSQL?","Khác biệt SQL và NoSQL?"),
("SQL is relational; NoSQL is flexible.","SQL quan hệ; NoSQL linh hoạt."),
("What is indexing?","Index là gì?"),
("Indexes speed up lookups.","Index tăng tốc tra cứu."),
("Explain ACID properties.","Giải thích thuộc tính ACID."),
("What is eventual consistency?","Nhất quán cuối cùng là gì?"),
("How do you handle conflicts?","Bạn xử lý xung đột thế nào?"),
("I prioritize and communicate early.","Tôi ưu tiên và báo sớm."),
("Describe a tough bug you fixed.","Kể về lỗi khó bạn từng sửa."),
("It was a race condition in cache.","Đó là race condition trong cache."),
("I added locks and tests.","Tôi thêm lock và test."),
("How do you learn new tech?","Bạn học công nghệ mới thế nào?"),
("I build small side projects.","Tôi làm dự án nhỏ bên lề."),
("I read docs and source code.","Tôi đọc tài liệu và mã nguồn."),
("Why do you want this job?","Vì sao bạn muốn công việc này?"),
("Your product impacts millions.","Sản phẩm của bạn ảnh hưởng hàng triệu người."),
("I align with your mission.","Tôi đồng điệu với sứ mệnh của bạn."),
("What are your strengths?","Điểm mạnh của bạn là gì?"),
("I'm detail-oriented and reliable.","Tôi tỉ mỉ và đáng tin cậy."),
("How do you handle pressure?","Bạn chịu áp lực thế nào?"),
("I break work into small steps.","Tôi chia việc thành bước nhỏ."),
("Rate your English communication.","Đánh giá giao tiếp tiếng Anh của bạn."),
("I can discuss technical topics fluently.","Tôi thảo luận kỹ thuật trôi chảy."),
("Are you okay with on-call duty?","Bạn trực on-call được không?"),
("Yes, with fair rotation.","Được, nếu xoay ca công bằng."),
("What's your expected salary?","Lương mong muốn của bạn?"),
("Around one thousand dollars.","Khoảng một nghìn đô."),
("I'm open to negotiation.","Tôi sẵn sàng thương lượng."),
("Do you have any questions for us?","Bạn có câu hỏi nào cho chúng tôi?"),
("What's the team structure?","Cấu trúc nhóm thế nào?"),
("How is success measured here?","Thành công được đo thế nào ở đây?"),
("What does the onboarding look like?","Onboarding diễn ra thế nào?"),
("Which tech stack will I use?","Tôi sẽ dùng stack nào?"),
("Is remote work allowed?","Có được làm remote không?"),
("How often are performance reviews?","Bao lâu đánh giá hiệu suất một lần?"),
("Thank you for the opportunity.","Cảm ơn vì cơ hội."),
("I look forward to hearing from you.","Tôi mong nhận tin từ bạn."),
("Live coding makes me nervous.","Live coding làm tôi hồi hộp."),
("May I think aloud?","Tôi nói to suy nghĩ được không?"),
("First, clarify requirements.","Đầu tiên, làm rõ yêu cầu."),
("Let's consider edge cases.","Xét các trường hợp biên."),
("Brute force first, optimize later.","Làm brute force trước, tối ưu sau."),
("Time complexity is O(n log n).","Độ phức tạp thời gian O(n log n)."),
("Space complexity is O(n).","Độ phức tạp không gian O(n)."),
("Can I use a hash map here?","Tôi dùng hash map ở đây được không?"),
("Let's dry-run with an example.","Chạy thử với ví dụ nhé."),
("Does this handle empty input?","Cách này xử lý đầu vào rỗng chứ?"),
("I'll write tests for it.","Tôi sẽ viết test cho nó."),
("Refactor for readability.","Refactor để dễ đọc."),
("How would you scale this?","Bạn mở rộng hệ thống này thế nào?"),
("Add caching and load balancing.","Thêm cache và cân bằng tải."),
("Use message queues for spikes.","Dùng hàng đợi tin nhắn khi tải tăng."),
("Design a URL shortener.","Thiết kế trình rút gọn URL."),
("Generate unique IDs with base62.","Sinh ID duy nhất bằng base62."),
("Handle redirects in milliseconds.","Xử lý chuyển hướng trong mili giây."),
("Design rate limiter next.","Tiếp theo thiết kế giới hạn tốc độ."),
("Token bucket is a common approach.","Token bucket là cách phổ biến."),
("System design is about trade-offs.","Thiết kế hệ thống là đánh đổi."),
("Choose consistency over availability here.","Ở đây chọn nhất quán hơn sẵn sàng."),
("Draw the architecture diagram.","Vẽ sơ đồ kiến trúc."),
("Explain data flow step by step.","Giải thích luồng dữ liệu từng bước."),
("Estimate QPS and storage.","Ước tính QPS và lưu trữ."),
("Behavioral: Tell me about conflict.","Câu hành vi: Kể về xung đột."),
("I listened, then proposed options.","Tôi lắng nghe rồi đề xuất lựa chọn."),
("We compromised and delivered on time.","Chúng tôi thỏa hiệp và giao đúng hạn."),
("I admitted my mistake quickly.","Tôi nhanh chóng nhận lỗi."),
("I asked for feedback proactively.","Tôi chủ động xin góp ý."),
("Failure taught me to test more.","Thất bại dạy tôi test nhiều hơn."),
("I stay calm under tight deadlines.","Tôi bình tĩnh trước deadline gấp."),
("I help teammates unblock fast.","Tôi giúp đồng đội gỡ kẹt nhanh."),
("Culture fit matters to me.","Hợp văn hóa quan trọng với tôi."),
("I value transparency and ownership.","Tôi coi trọng minh bạch và trách nhiệm."),
("I'm excited to contribute!","Tôi háo hức được đóng góp!"),
]
for en, vi in interview:
    add(en, vi, "tech", "Phỏng vấn xin việc", "B2")

# ---------- 10. AI / DATA (90) ----------
ai = [
("AI is transforming every industry.","AI đang thay đổi mọi ngành."),
("Machine learning learns from data.","Học máy học từ dữ liệu."),
("Deep learning uses neural networks.","Học sâu dùng mạng nơ-ron."),
("LLMs can understand and generate text.","LLM có thể hiểu và sinh văn bản."),
("Prompt engineering improves outputs.","Kỹ thuật prompt cải thiện đầu ra."),
("Be specific in your prompts.","Hãy cụ thể trong prompt."),
("Give examples (few-shot prompting).","Cho ví dụ (few-shot prompting)."),
("Set the role: 'Act as an expert...'","Đặt vai trò: 'Hãy đóng vai chuyên gia...'"),
("Control creativity with temperature.","Điều chỉnh sáng tạo bằng temperature."),
("Lower temperature means focused answers.","Temperature thấp cho câu trả lời tập trung."),
("RAG combines retrieval with generation.","RAG kết hợp truy xuất và sinh văn bản."),
("Chunk documents before embedding.","Chia nhỏ tài liệu trước khi nhúng."),
("Vector databases store embeddings.","Database vector lưu embeddings."),
("Cosine similarity measures closeness.","Độ tương đồng cosine đo sự gần nhau."),
("Evaluate models with benchmarks.","Đánh giá mô hình bằng benchmark."),
("Watch out for hallucinations.","Cẩn thận với ảo giác của AI."),
("Always verify AI-generated facts.","Luôn kiểm chứng thông tin do AI tạo."),
("Human-in-the-loop is safer.","Có người giám sát sẽ an toàn hơn."),
("Fine-tune on your domain data.","Fine-tune trên dữ liệu chuyên ngành."),
("Pretraining needs huge compute.","Pretrain cần tài nguyên tính toán lớn."),
("Inference must be fast and cheap.","Suy luận phải nhanh và rẻ."),
("Quantization reduces model size.","Lượng tử hóa giảm kích thước mô hình."),
("Distillation creates smaller models.","Chưng cất tạo mô hình nhỏ hơn."),
("Edge AI runs on devices.","Edge AI chạy trên thiết bị."),
("Data quality beats quantity.","Chất lượng dữ liệu hơn số lượng."),
("Clean duplicates before training.","Làm sạch trùng lặp trước khi huấn luyện."),
("Label data consistently.","Gán nhãn dữ liệu nhất quán."),
("Split data into train/val/test.","Chia dữ liệu thành train/val/test."),
("Avoid data leakage!","Tránh rò rỉ dữ liệu!"),
("Overfitting means memorizing noise.","Overfitting là học thuộc nhiễu."),
("Regularization prevents overfitting.","Chính quy hóa chống overfitting."),
("Cross-validation gives robust estimates.","Kiểm định chéo cho ước tính vững."),
("Track experiments with MLflow.","Theo dõi thử nghiệm bằng MLflow."),
("Version your datasets.","Đánh phiên bản cho tập dữ liệu."),
("Monitor model drift in production.","Giám sát trôi mô hình ở production."),
("Retrain when performance drops.","Huấn luyện lại khi hiệu suất giảm."),
("A/B test model versions.","A/B test các phiên bản mô hình."),
("Explain predictions with SHAP.","Giải thích dự đoán bằng SHAP."),
("Bias in data causes unfair models.","Thiên lệch dữ liệu gây mô hình bất công."),
("Audit models for fairness.","Kiểm toán mô hình về công bằng."),
("Anonymize personal data.","Ẩn danh dữ liệu cá nhân."),
("Comply with data regulations.","Tuân thủ quy định dữ liệu."),
("Python dominates data science.","Python thống trị khoa học dữ liệu."),
("Pandas makes data wrangling easy.","Pandas giúp xử lý dữ liệu dễ dàng."),
("Visualize with Matplotlib or Plotly.","Trực quan hóa bằng Matplotlib hoặc Plotly."),
("SQL is still essential.","SQL vẫn rất cần thiết."),
("JOIN tables to combine data.","JOIN bảng để kết hợp dữ liệu."),
("GROUP BY aggregates rows.","GROUP BY gom nhóm hàng."),
("Window functions rank rows.","Hàm cửa sổ xếp hạng hàng."),
("Handle missing values carefully.","Xử lý giá trị thiếu cẩn thận."),
("Normalize features before training.","Chuẩn hóa đặc trưng trước khi huấn luyện."),
("One-hot encode categories.","Mã hóa one-hot cho biến phân loại."),
("Feature engineering boosts accuracy.","Kỹ thuật đặc trưng tăng độ chính xác."),
("Start with a simple baseline.","Bắt đầu với baseline đơn giản."),
("Gradient descent minimizes loss.","Gradient descent tối thiểu hóa mất mát."),
("Tune learning rate first.","Tinh chỉnh learning rate trước."),
("Early stopping saves time.","Dừng sớm tiết kiệm thời gian."),
("Save the best checkpoint.","Lưu checkpoint tốt nhất."),
("Deploy models with FastAPI.","Triển khai mô hình bằng FastAPI."),
("Containerize the inference service.","Đóng gói dịch vụ suy luận bằng container."),
("Autoscale GPU workers.","Tự động mở rộng worker GPU."),
("Cache frequent predictions.","Cache các dự đoán thường gặp."),
("Log inputs for auditing.","Log đầu vào để kiểm toán."),
("Tokens determine API cost.","Token quyết định chi phí API."),
("Batch requests to save money.","Gộp request để tiết kiệm."),
("Stream responses for better UX.","Stream phản hồi để UX tốt hơn."),
("Set max tokens to control length.","Đặt max token để kiểm soát độ dài."),
("Function calling connects AI to tools.","Function calling nối AI với công cụ."),
("Agents plan and use tools stepwise.","Agent lập kế hoạch và dùng công cụ từng bước."),
("Give agents clear guardrails.","Đặt giới hạn rõ cho agent."),
("Review agent actions before executing.","Xem lại hành động của agent trước khi chạy."),
("Chatbots need fallback responses.","Chatbot cần câu trả lời dự phòng."),
("Personalize without being creepy.","Cá nhân hóa mà không gây khó chịu."),
("Summarize long docs with AI.","Tóm tắt tài liệu dài bằng AI."),
("Translate with context preserved.","Dịch mà giữ nguyên ngữ cảnh."),
("Transcribe meetings automatically.","Tự động ghi âm cuộc họp."),
("Detect spam with classifiers.","Phát hiện spam bằng bộ phân loại."),
("Recommend products users love.","Gợi ý sản phẩm người dùng thích."),
("Forecast sales with time series.","Dự báo doanh số bằng chuỗi thời gian."),
("Detect anomalies in logs.","Phát hiện bất thường trong log."),
("Cluster customers by behavior.","Phân nhóm khách hàng theo hành vi."),
("Segment users for campaigns.","Phân khúc người dùng cho chiến dịch."),
("Measure precision and recall.","Đo precision và recall."),
("F1 balances both metrics.","F1 cân bằng cả hai chỉ số."),
("ROC-AUC evaluates ranking.","ROC-AUC đánh giá xếp hạng."),
("Data storytelling convinces stakeholders.","Kể chuyện bằng dữ liệu thuyết phục stakeholder."),
("Dashboards should answer one question.","Dashboard nên trả lời một câu hỏi."),
("Less is more in visualization.","Ít mà chất trong trực quan hóa."),
("AI won't replace you, but...","AI không thay thế bạn, nhưng..."),
("...someone using AI might!","...người biết dùng AI có thể!"),
("Keep learning every day.","Hãy học mỗi ngày."),
]
for en, vi in ai:
    add(en, vi, "tech", "AI & dữ liệu", "B2")

print(f"Total: {len(sentences)}")
assert len(sentences) == 1000, len(sentences)
with open("data/sentences.json","w",encoding="utf-8") as f:
    json.dump(sentences, f, ensure_ascii=False, indent=1)
print("saved")
